const evn="dev";
const  baseUrl={
    worker:"http://"+evn+".worker.service.xieqj.net:30001/",
    security:"http://"+evn+".security.xieqj.net:10082/",
    oss:"http://"+evn+".security.xieqj.net:10020/",
}
const urls={
    authUrl:baseUrl.security+"api/login/IsLogin",
    loginUrl:baseUrl.security+"api/login/Login",
    upUrl:baseUrl.oss+"file/img",
    company_pager_url:baseUrl.worker+"company/pager",
    company_list_url:baseUrl.worker+"company/list",
    company_get_url:baseUrl.worker+"company/get",
    company_add_url:baseUrl.worker+"company/add",
    company_edit_url:baseUrl.worker+"company/edit",
    company_del_url:baseUrl.worker+"company/del",
    department_pager_url:baseUrl.worker+"department/pager",
    department_get_url:baseUrl.worker+"department/get",
    department_list_url:baseUrl.worker+"department/list",
    department_add_url:baseUrl.worker+"department/add",
    department_edit_url:baseUrl.worker+"department/edit",
    department_del_url:baseUrl.worker+"department/del",
    job_pager_url:baseUrl.worker+"job/pager",
    job_list_url:baseUrl.worker+"job/list",
    job_get_url:baseUrl.worker+"job/get",
    job_add_url:baseUrl.worker+"job/add",
    job_edit_url:baseUrl.worker+"job/edit",
    job_set_url:baseUrl.worker+"job/set",
    job_del_url:baseUrl.worker+"job/del",
    person_pager_url:baseUrl.worker+"person/pager",
    person_get_url:baseUrl.worker+"person/get",
    person_list_url:baseUrl.worker+"person/list",
    person_add_url:baseUrl.worker+"person/add",
    person_edit_url:baseUrl.worker+"person/edit",
    person_del_url:baseUrl.worker+"person/del",
    user_pager_url:baseUrl.worker+"user/pager",
    user_get_url:baseUrl.worker+"user/get",
    user_add_url:baseUrl.worker+"user/add",
    user_edit_url:baseUrl.worker+"user/edit",
    user_del_url:baseUrl.worker+"user/del",
}
export default urls